runtime: python311

entrypoint: gunicorn -b :$PORT main:app

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  min_idle_instances: 1
  max_idle_instances: automatic
  min_pending_latency: 30ms
  max_pending_latency: automatic

env_variables:
  ENVIRONMENT: production
  LOG_LEVEL: INFO
  GCP_PROJECT_ID:	zippy-aurora-482207-a2

liveness_check:
  path: /health
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

readiness_check:
  path: /health
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300

handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
