runtime: python311

entrypoint: gunicorn -b :$PORT main:app

env_variables:
  DB_PASSWORD: "projects/opportune-lore-482118-q1/secrets/db-password/versions/latest"
  API_KEY: "projects/opportune-lore-482118-q1/secrets/api-key/versions/latest"

automatic_scaling:
  min_instances: 0
  max_instances: 1
