steps:
  - name: gcr.io/cloud-builders/gcloud
    args:
      - app
      - deploy
      - --quiet
      - --service-account=appengine-deployer@opportune-lore-482118-q1.iam.gserviceaccount.com

timeout: "1200s"
