# Cloud Build configuration for Python Flask App Engine deployment
# This file is triggered automatically by Git webhooks

steps:
  # Step 1: Install dependencies (for testing)
  - name: 'python:3.11'
    id: 'install-dependencies'
    entrypoint: 'pip'
    args: ['install', '-r', 'requirements.txt', '--user']
    
  # Step 2: Run tests (if you have them)
  # Uncomment when you add tests
  # - name: 'python:3.11'
  #   id: 'run-tests'
  #   entrypoint: 'python'
  #   args: ['-m', 'pytest', 'tests/']
  #   waitFor: ['install-dependencies']
  #   env:
  #     - 'ENVIRONMENT=test'
    
  # Step 3: Deploy to App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deploy-to-appengine'
    args:
      - 'app'
      - 'deploy'
      - 'app.yaml'
      - '--quiet'
      - '--promote'
      - '--stop-previous-version'
    timeout: '1600s'

# CRITICAL: Service account to use for deployment
# Replace with your service account email
serviceAccount: 'projectsapp-engine-ci-cd@zippy-aurora-482207-a2.iam.gserviceaccount.com'

# Build timeout
timeout: '2000s'

# Build options
options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
  
# Tags for organization
tags: ['app-engine', 'python', 'production', 'automated-deployment']

# Note: Secrets are NOT accessed in Cloud Build
# They are accessed at runtime by the application using Secret Manager client library
# This is more secure than passing secrets through environment variables
