steps:
# Step 1: Fetch secrets
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      echo "Fetching secrets..."
      export DB_PASSWORD=$(gcloud secrets versions access latest --secret=db-password)
      export API_KEY=$(gcloud secrets versions access latest --secret=api-key)

      echo "Deploying to App Engine..."
      gcloud app deploy app.yaml --quiet

timeout: '1200s'

options:
  logging: CLOUD_LOGGING_ONLY
